name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # إجبار السيرفر على استخدام إصدار Gradle 8.5 المتوافق ومنع التحديث التلقائي لـ 9.0
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.5'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      continue-on-error: true

    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: PlayAssist-v1-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
